INSERT INTO PERSON (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('FRANK', 'MOLEY', 'FRANKMOLEY@GMAIL.COM');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('GEORGE', 'WASHINGTON', 'GEORGEWASHINGTON@US.GOV');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('DHARMENDRA', 'PANDIT', 'DHARMENDRA.PANDIT@CAPGEMINI.COM');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('GAGAN', 'GALANDE', 'GAGAN.GALENDE@CAPGEMINI.COM');
